# Generated by Django 4.2.29 on 2026-03-11 05:20

import apps.workspaces.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Analysis'), ('analyzed', 'Analyzed')], default='draft', max_length=10)),
                ('total_uploads_today', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.workspaces.models.source_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('ext', models.CharField(max_length=10)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.workspaces.models.document_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('ext', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('check', 'Document to Check')], default='check', max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.workspace')),
            ],
        ),
    ]
