# Generated by Django 4.2.29 on 2026-03-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('checks_per_month', models.IntegerField(default=10, help_text='-1 means unlimited')),
                ('max_sources', models.IntegerField(default=5, help_text='-1 means unlimited')),
                ('max_documents', models.IntegerField(default=3, help_text='-1 means unlimited')),
                ('allowed_formats', models.JSONField(default=list, help_text='e.g. ["pdf","docx","txt"]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
